apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: managed
spec:
  interval: 1m
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: managed
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      version: '6.9.1'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: managed
      interval: 5m
  # values:
  #   replicaCount: 2