apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: managed
spec:
  interval: 1m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: managed
spec:
  interval: 2m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.13.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: managed
      interval: 5m
  # values:
  #   replicaCount: 2