apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: roundrobin
spec:
  resourceRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    matchLabels:
      app: podinfo
  strategy:
    type: roundRobin
    dnsTtlSeconds: 30