ui:
  color: "#fab41e"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    k8gb.io/strategy: failover
    kubernetes.io/ingress.class: nginx

  hosts:
    - paths:
        - path: /
          pathType: ImplementationSpecific
