ui:
  color: "#fab41e"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    k8gb.io/strategy: failover
    kubernetes.io/ingress.class: nginx

  hosts:
    - paths:
        - path: /
          pathType: ImplementationSpecific

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: podinfo
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: podinfo