apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8gb
  namespace: managed
spec:
  interval: 1m
  url: https://www.k8gb.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8gb
  namespace: managed
spec:
  interval: 2m
  chart:
    spec:
      chart: k8gb
      version: '0.14.0'
      sourceRef:
        kind: HelmRepository
        name: k8gb
        namespace: managed
      interval: 10m
  # values:
  #   replicaCount: 2